### ISSUE TITLE
Use AtStartOfList and LastScrollDirection in ViewModel

### ISSUE THREAD

**Issue by lvkz** [david-js/XFListViewInfo#1]
Hey David, thank you so much for this!

I'm having issues translating it into a real scenario though. I need the status of AtStartOfList and LastScrollDirection in the ViewModel, but since the example binds these to the view, I can't figure out how to send it back to the ViewModel which is controlling the ItemsSource of the list and is going to modify the list items later on filtering. 

I was wondering if you can point me in the right direction.

Thanks in advance!

**Comment by david-js** [comment]
<p>Glad it's helpful!  Check out the <a href="https://github.com/david-js/XFListViewInfo/tree/useviewmodel">useviewmodel branch</a>.  I introduced MainPageViewModel, which is getting updates of AtStartOfList and LastScrollDirection, which is causing the view to be updated. I changed the names a bit in the view model to make it easier to see what's going on (ScrollingDirection vs. LastScrollDirection).</p>

<p>The key is to bind the view model properties to LastScrollDirection/AtStartOfList using Mode=OneWayToSource.  See the use of <local:MyListView> in <a href="https://github.com/david-js/XFListViewInfo/blob/useviewmodel/ListInfoDemo/ListInfoDemo/MainPage.xaml">MainPage.xaml</a>.</p>

<p>Hope that helps!</p>

**Comment by lvkz** [comment]
Awesome!! Thank you very much!! It worked!!

Now I'm facing another issue, for some reason I had to add a "delay" on the "ShouldShowSearchBar" method: 

```
System.Threading.Tasks.Task.Delay(75).Wait();
return shouldChange ? newValue : _lastShowValue.Value;
```

Otherwise, it wouldn't show the search bar on load. (The appear/disappear functionality works thou). Any insights on why I have to add that delay to make it work? (I'm loading the element list remotely).

**Comment by david-js** [comment]
If you get rid of the anti-jitter delay, you end up with a pretty jarring user experience, but what you'll want is a way to temporarily suspend the anti-jitter code.  Your code to load the list would look something like this:  

```
    async Task MyLoadingMethod() {
        // other stuff  
        var newList = await LoadMyData();  
        viewmodel.SuspendSearchBarAntiJitter = true;
        viewmodel.TheList = newList;
        viewmodel.SuspendSearchBarAntiJitter = false;
        // more stuff
    }
```
Then in the getter for ShouldShowSearchBar, shouldChange would always be set to set to true if SuspectSearchBarAntiJitter is true.

Let me know how it goes.

**Comment by lvkz** [comment]
So, as you suggested I ended up adding a boolean to my viewModel: 

`public bool SuspendSearchBarAntiJitter { get; set; }`

And modified my `ShouldShowSearchBar` property to take in consideration the value of the `SuspendSearchBarAntiJitter`: 

`shouldChange = SuspendSearchBarAntiJitter ? true : shouldChange;`

Then in my view class when I was loading the data, `OnAppearing()`, added the changes you suggested, so ended up looking like this: 

`viewModel.SuspendSearchBarAntiJitter = true;`
`viewModel.PullAssociatedHostCommand.Execute(null);`
`viewModel.SuspendSearchBarAntiJitter = false;`

But it wasn't working, so I added the `true` at the constructor, before `InitializeComponent`:

```
public MyView()
{
    BindingContext = viewModel = new HostsViewModel();
    //Initializing some stuff...
    viewModel.SuspendSearchBarAntiJitter = true;

    InitializeComponent();
}
```
And then it worked!! Thank you very much for your time and your code!!!
